name: sudoku
description: Proudly Indian Logic Game - Sudoku by Perfeasy
publish_to: 'none'
version: 0.1.2+37

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # State Management  
  provider: ^6.1.1
  
  # AdMob Integration
  google_mobile_ads: ^3.0.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  
  # Voice & Animation (commented out for minimal build)
  # flutter_tts: ^3.8.5
  # animated_text_kit: ^4.2.2
  # lottie: ^3.1.2
  
  # External Character Support (commented out for minimal build)
  # rive: ^0.12.4
  # video_player: ^2.8.2
  
  # Audio Support (commented out for minimal build)
  # audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    # - assets/audio/music/
    # - assets/audio/sfx/
    # - assets/characters/
    # - assets/live_action/

